#!/bin/bash
year=$(echo "$1" | sed -r 's/([0-9]\{4\})[0-9a-zA-Z._]*$/\1/')
month=$(echo "$1" | sed -r 's/^[0-9]\{4\}([0-9]\{2\})[0-9a-zA-Z._]*$/\1/')
dir="./$year/$month/"
mkdir -p "$dir"
mv "$1" "$dir"

