#!/bin/bash

#Photosort--A photo-sorting script
#Copyright (C) 2011  andyg0808 

#This program is free software; you can redistribute it and/or
#modify it under the terms of the GNU General Public License
#as published by the Free Software Foundation; either version 2
#of the License, or (at your option) any later version.

#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.

#You should have received a copy of the GNU General Public License
#along with this program; if not, write to the Free Software
#Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

if [ -z "$1" -o -z "$2" ]
then
echo "Usage: $(basename $0) folder_of_unsorted folder_of_sorted"
exit
fi

#Find duplicate files
#Goes through the specified directories recursively, deleting duplicate files.
#Only deletes the second and greater copy of each file.
#Checks the sorted files first, to (hopefully) prevent them from being deleted
#and replaced.
fdupes --recurse --delete --noprompt "$2" "$1"

#Now that the duplicates are stripped, rename all the files with rndate.
find "$1" -type f -execdir rndate '{}' \;

#Move all the files to their new locations according to their names
find "$1" -type f -execdir pixmv '{}' "$PWD/$2" \;

#Delete now-empty directories
find "$1"/* "$2"/* -type d -empty -delete



#cat ../Partition1/duplicateslist | xargs rm -vv

#find -type d -execdir "exiv2 mv *.jpg"

#find Unsorted/ -type f -exec rnmoddate '{}' \;

#find Unsorted/ -type f -exec exiv2 -F mv '{}' +

#find -type f Unsorted/ -execdir rnmoddate '{}' \;


