#!/bin/bash

#If exiv2 can rename the file, let it.
if exiv2 -v -F rename "$1"
then
echo "Renamed $1 with exiv2"
exit
fi

date=$(stat -c%y "$1" | ssed -R 's/\..*//')
ext=$(echo "$1" | ssed -R 's/.*?(\.[^.]+)?$/\1/')
head=$(dirname "$1")

#Check if the file's current name is the same as the new name
if [ "$(basename $1)" == "$date$ext" ]
then
exit
fi

#Change the file's name to the new one. Avoid overwriting other files with the
#same date.
if [ ! -e "$head/$date$ext" ]
then
#Output the old and new names of this file
echo "$1" "$head/$date$ext"

#Move the file. The --no-clobber is a precaution against some bug causing an
#inadvertant overwrite
mv --no-clobber "$1" "$head/$date$ext"
else

suf=1

while [ -e "$head/${date}_$suf$ext" ]
do
#Increment the suffix value
let suf++
done

echo "Substitute name:"
echo "$1" "$head/${date}_$suf$ext"

#We must now have found a suffix that works--move the file to that name
mv --no-clobber "$1" "$head/${date}_$suf$ext"
fi
echo "Renamed $1 with modified date"
